[package]
name = "rust-desert-sunset"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wgpu = "0.19"
glam = "0.25"
env_logger = "0.11"
log = "0.4"
pollster = "0.3"
cfg-if = "1.0.4"
bytemuck = { version = "1.25.0", features = ["derive"] }
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
winit = "0.29"
egui = { version = "0.27.0", default-features = false, features = ["default_fonts"] }
egui-wgpu = "0.27.0"
egui-winit = { version = "0.27.0", default-features = false, features = ["links"] }
web-time = "1.1.0"
cpal = "0.15"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
console_error_panic_hook = "0.1.7"
console_log = "1.0"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "HtmlCanvasElement",
    "HtmlInputElement",
    "EventTarget",
    "Event",
    "AudioContext",
    "AudioDestinationNode",
    "AudioBuffer",
    "AudioBufferSourceNode",
    "GainNode",
    "BiquadFilterNode",
    "BiquadFilterType",
    "AudioParam",
    "AudioContextState",
    "OscillatorNode",
    "OscillatorType"
] }
wasm-bindgen-futures = "0.4.72"

[package.metadata.bundle]
name = "Desert Sunset"
identifier = "com.pepeamoedo.desertsunset"
icon = ["icon.icns"]

[profile.release]
opt-level = 3        # Máxima optimización de velocidad (usa "s" o "z" si prefieres menor peso)
lto = true           # Link Time Optimization (elimina código muerto entre librerías)
codegen-units = 1    # Compila todo de golpe para maximizar la optimización (más lento al compilar, más rápido al ejecutar)
panic = "abort"      # Elimina el código de "unwinding" de errores (reduce peso del WASM)
